name: Docker

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into DockerHub
        uses: docker/login-action@v1
        if: ${{ github.event_name != 'pull_request' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set VERSION env var
        run: |
          echo "VERSION=$(cat package.json | jq -r '.version')" >> $GITHUB_ENV

      - name: Build Docker image, and push if tagged
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name == 'create' }}
          tags: wywywywy/tesla_exporter:latest,wywywywy/tesla_exporter:${{ env.VERSION }}
          platforms: linux/amd64,linux/arm64
